kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBuro2p04FYAIHDKcZz7/sCwajvUcbPI3UfbSaFxWuOsm00srJc8Av/nMZ0fVqm4UZxHc57qLGOFnORDhbsv/d7+FZXL54b8V2hxk82K3/41AWMwbEggbsCW3aTd5zvF/t7YeC0aI2v1r5ZsJpZtM3gSMMzHSKxhCSLx9vZ7n7jGvhBkxjlYp1wRBrIt7vrvRsgMj9gtjV9/2Ol60dI1tEW0KS0SGDvNGCoH5/K/+ijuphcRsuW9tK9MXu7VmT1abiADU/vV/dFScgbfZ9JFg4B5olsQ4JLoZ9MVpDjNnL6TqoU22nVw6UEUNS60wSj5lYsKk/1DHujC0mU/FM5sQ9kpv5HrutKZGp6gXfq4cZ2R/onxJEy/LZJQ2IIYnqtG3T8qeaeSpcN5qnNLAf34X32O1JNZKkFoR9ge9anqhL2wDF0NCfIjSaqdwZoRIo5QvzIdjUJ1X3WEzu157gQlBKebj+/3mYNkbY4pwGdgj3cqcjwkYgMN5bBzXk7+0i/XG6ljaA7+JH34YarlywdFBemYWI/Lj94APis0FM7h67cU6Mv/yumoljA/Ar7B7/yilkmHVUK/PZ1JOsVOxjM0h6JWAFn9YAvxL+QShec58ACtljCv7iFr2xtwtW1SH2sJr/dbZRdGxXD/2lq4ElCAaLejoGCr46ddTRNn7MvN31JYfu+fJmXAh9CEuXbJix817TlR0eN
    admin-user: AgAbdGsZBxz0jJoQH4S+8zMlCnKUIUO0MRUFwUlBDLoOrfqK9bKPSOZ1QWIJ7FrAUMpQVvkQBlycRgmAcoYVM/PYiYsFeJdKWKKZFLhTdtszQ9Cy5GYgxS87I5wyG/hvj7R//5Iky/lpPW3rahXJhEQreBCr6ATwtNZIpcEp/aDFr3Wt3GfmAEZ4T+Skejl9I7jAHWlrm3cD2PoFgfB8/sDzoZoe9BCH9j4PeCnXT4k/pTqer4oNM1jKvTaD/NuCOgMlTTHCfl7wlrb2UoJzHzD7cIN17fJoqQRBqCbDzmiHu716I3RdyBW069WHIq3nTZkX8sMhe5ST9CYQ3DnW3OzOTsxH+CLOb1exM56p4p/QZ06qeH6rgcW1fZGzHgTaucW6VSkjIZpc2mwcJGypPWlvMQRPzKZ6Qf23BT336hOWdIBubH4Pq3PUMptXWv8bq84Q8LSLCMrQYW3684Pg7NwBMwucdAtyIVBy8Gr6YM4dOJCSVGPzIqDofIZDSOjVUUOc8U4aBnlbzwIzY3vqfmGctxAlHzyYdf/CjY4qEj42ef+QW7nmUGDnkXJEm7qYkopBTm/LInRpAT2eW1w4178CNVN0zP0pQatHG3NAlAtQ+hhmWPj8sgi3zXQ6Mb4wzpom1lViTOz6mzMKLHDpWYrLc8xFMRwKe2QZWYovfBneJPyciN9+w686D9XlG3UjytEzjQWhdw==
